### ISSUE TITLE
In Predicting Intensive Care Delirium with Machine Learning: Model Development and External The problem of algorithm replication in the Validation article

### ISSUE THREAD

**Issue by mengqings** [ryanlu41/delirium#1]
On line 50 of the "FindingChartEventDelirimInfo. py" file, you read the "CHARTEVENTS. csv" file and want to obtain the "LABEL" column. From your article, can see that you are using the MIMICii database, but the label column is not included in the CSV file. I created a new 'LABEL' in the py file, which is an empty column and still reported an error when running the 'GetChartEventDelirimInfo. py' file.

So I would like to ask how you obtained the "LABEL" column, or is my data not being used

**Comment by mengqings** [comment]
On line 50 of the "FindingChartEventDelirimInfo. py" file, you read the "CHARTEVENTS. csv" file and want to obtain the "LABEL" column. From your article, can see that you are using the MIMICii database, but the label column is not included in the CSV file. I created a new 'LABEL' in the py file, which is an empty column and still reported an error when running the 'GetChartEventDelirimInfo. py' file.

So I would like to ask how you obtained the "LABEL" column, or is my data not being used

**Comment by mengqings** [comment]
在“FindingChartEventDelirimInfo.py”文件第50行代码您读取“CHARTEVENTS.csv”文件，并希望获得“LABEL”列。从您的文章中，您可以看到您使用的是MIMICiii数据库，但是在该csv文件中并不包含label列。我在py文件中创建了一个新的“LABEL”，是个空的列在运行“GetChartEventDelirimInfo.py”文件时仍然报告了一个错误。

所以我想问您是如何获得“LABEL”列的，还是我数据没有使用对

**Comment by Drwr97** [comment]
How did you solve it？
